In [36]:
import numpy as np


In [703]:
Iris = np.genfromtxt("Documents\\FisherIris_ML.csv", delimiter=",")
Iris
        

array([[  2.,  14.,  33.,  50.,   0.],
       [ 24.,  56.,  31.,  67.,   1.],
       [ 23.,  51.,  31.,  69.,   1.],
       [  2.,  10.,  36.,  46.,   0.],
       [ 20.,  52.,  30.,  65.,   1.],
       [ 19.,  51.,  27.,  58.,   1.],
       [ 13.,  45.,  28.,  57.,   2.],
       [ 16.,  47.,  33.,  63.,   2.],
       [ 17.,  45.,  25.,  49.,   1.],
       [ 14.,  47.,  32.,  70.,   2.],
       [  2.,  16.,  31.,  48., -10.],
       [ 19.,  50.,  25.,  63.,   1.],
       [  1.,  14.,  36.,  49.,   0.],
       [  2.,  13.,  32.,  44.,   0.],
       [ 12.,  40.,  26.,  58.,   2.],
       [ 18.,  49.,  27.,  63.,   1.],
       [ 10.,  33.,  23.,  50.,   2.],
       [  2.,  16.,  38.,  51.,   0.],
       [  2.,  16.,  30.,  50.,   0.],
       [ 21.,  56.,  28.,  64.,   1.],
       [  4.,  19.,  38.,  51.,   0.],
       [  2.,  14.,  30.,  49.,   0.],
       [ 10.,  41.,  27.,  58.,   2.],
       [ 15.,  45.,  29.,  60., -12.],
       [  2.,  14.,  36.,  50.,   0.],
       [ 19.,  51.,  27.,

In [704]:
Iris.shape 

(150, 5)

In [705]:
Iris[:, 4:5] 

array([[  0.],
       [  1.],
       [  1.],
       [  0.],
       [  1.],
       [  1.],
       [  2.],
       [  2.],
       [  1.],
       [  2.],
       [-10.],
       [  1.],
       [  0.],
       [  0.],
       [  2.],
       [  1.],
       [  2.],
       [  0.],
       [  0.],
       [  1.],
       [  0.],
       [  0.],
       [  2.],
       [-12.],
       [  0.],
       [  1.],
       [  0.],
       [  1.],
       [  2.],
       [  0.],
       [  1.],
       [  2.],
       [  0.],
       [  2.],
       [  1.],
       [  2.],
       [  1.],
       [  1.],
       [  2.],
       [  2.],
       [  2.],
       [  1.],
       [  1.],
       [  2.],
       [  1.],
       [  0.],
       [  0.],
       [  2.],
       [  0.],
       [  2.],
       [  1.],
       [  1.],
       [  2.],
       [  2.],
       [  2.],
       [  1.],
       [  1.],
       [  1.],
       [-10.],
       [  2.],
       [  1.],
       [  1.],
       [  2.],
       [  1.],
       [  0.],
       [  0.],
       [  

In [706]:
np.where(Iris <0);

In [707]:
print(np.where(Iris <0));

(array([ 10,  23,  58,  89, 108, 136], dtype=int64), array([4, 4, 4, 4, 4, 4], dtype=int64))


In [712]:
Iris = np.delete(Iris,[ 10,  23,  58,  89, 108, 136],axis=0)

In [778]:
print(Iris)

[[ 2. 14. 33. 50.  0.]
 [24. 56. 31. 67.  1.]
 [23. 51. 31. 69.  1.]
 [ 2. 10. 36. 46.  0.]
 [20. 52. 30. 65.  1.]
 [19. 51. 27. 58.  1.]
 [13. 45. 28. 57.  2.]
 [16. 47. 33. 63.  2.]
 [17. 45. 25. 49.  1.]
 [14. 47. 32. 70.  2.]
 [19. 50. 25. 63.  1.]
 [ 1. 14. 36. 49.  0.]
 [ 2. 13. 32. 44.  0.]
 [12. 40. 26. 58.  2.]
 [18. 49. 27. 63.  1.]
 [10. 33. 23. 50.  2.]
 [ 2. 16. 38. 51.  0.]
 [ 2. 16. 30. 50.  0.]
 [21. 56. 28. 64.  1.]
 [ 4. 19. 38. 51.  0.]
 [ 2. 14. 30. 49.  0.]
 [10. 41. 27. 58.  2.]
 [ 2. 14. 36. 50.  0.]
 [19. 51. 27. 58.  1.]
 [ 4. 15. 34. 54.  0.]
 [18. 55. 31. 64.  1.]
 [10. 33. 24. 49.  2.]
 [ 2. 14. 42. 55.  0.]
 [15. 50. 22. 60.  1.]
 [14. 39. 27. 52.  2.]
 [ 2. 14. 29. 44.  0.]
 [12. 39. 27. 58.  2.]
 [23. 57. 32. 69.  1.]
 [15. 42. 30. 59.  2.]
 [20. 49. 28. 56.  1.]
 [18. 58. 25. 67.  1.]
 [13. 44. 23. 63.  2.]
 [15. 49. 25. 63.  2.]
 [11. 30. 25. 51.  2.]
 [21. 54. 31. 69.  1.]
 [25. 61. 36. 72.  1.]
 [13. 36. 29. 56.  2.]
 [21. 55. 30. 68.  1.]
 [ 1. 14. 3

In [729]:
Iris.shape

(144, 5)

In [850]:
X = Iris [(0,1,2,3), :5]

In [851]:
print(X)

[[ 2. 14. 33. 50.  0.]
 [24. 56. 31. 67.  1.]
 [23. 51. 31. 69.  1.]
 [ 2. 10. 36. 46.  0.]]


In [852]:
Y = Iris [(4), :5]

In [853]:
print(Y)

[20. 52. 30. 65.  1.]


In [890]:
X.min(axis=1) 

array([0., 1., 1., 0.])

In [891]:
X.max(axis=1) 

array([50., 67., 69., 46.])

In [912]:
X[3:,:5] > 36

array([[False, False, False,  True, False]])

In [926]:
np.sum(X[3:,:5] > 36)

1